name: responsive_sizer_example
description: An example app that shows how to use the responsive_sizer package.

publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  responsive_sizer:
    path: ../

flutter:
  uses-material-design: true